DROP TABLE t_pet CASCADE CONSTRAINTS;
DROP TABLE t_aluno CASCADE CONSTRAINTS;
DROP TABLE t_professor CASCADE CONSTRAINTS;
DROP TABLE t_fundador CASCADE CONSTRAINTS;
DROP TABLE t_fantasma CASCADE CONSTRAINTS;
DROP TABLE t_casa CASCADE CONSTRAINTS;